handling not exist gracefully
Snowflake-Labs/terraform-provider-snowflake pull request #1031
Opened 2022-05-30 15:33 UTC by israel

This is my first PR here so I have made changes to only some of the resources. Once approved I will do the same for the rest. Thanks

Changed handling of not exists scenarios for read resource functions for User, API Integration and External Function resources

## Test Plan
Updated user_test to reflect the change.

## References

2022-05-31 22:27 UTC, sfc-gh-swinkler commented
Hello @israel, thank you for your PR!

I think this is good, just I would ask for you to create a new file called `errors.go` at `pkg/snowflake/errors.go` to declare this error as a constant. For example, take a look at how this provider did the same thing you are doing:
https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_team.go#L155-L162

and then they declared that error in the errors.go file:
https://github.com/hashicorp/go-tfe/blob/main/errors.go#L13

This is not something we are currently doing, but its a pattern I would like to start abiding by. If you could please do this I would be much obliged.

2022-06-07 18:39 UTC, israel commented
Hi @sfc-gh-swinkler 
Apologies for the delayed response, I have not seen the notification for some reason...
I have moved the generic error from external_function.go to a common errors file as you requested.
Thanks,
Israel

2022-06-10 23:54 UTC, sfc-gh-swinkler requested changes

2022-06-10 23:54 UTC, sfc-gh-swinkler commented on pkg/resources/api_integration.go
> +		if err.Error() == "sql: no rows in result set" {
this should be ErrNoRowInRS i think

2022-06-13 10:03 UTC, israel commented on pkg/resources/api_integration.go
> +		if err.Error() == "sql: no rows in result set" {
done

2022-06-16 17:27 UTC, sfc-gh-swinkler commented
/ok-to-test sha=7a8f66b

2022-06-16 17:44 UTC, sfc-gh-swinkler approved these changes

2022-06-16 17:44 UTC, merged

2022-06-16 17:44 UTC, sfc-gh-swinkler commented
Thank you for your contribution! @israel