Delete ownership grant updates
Snowflake-Labs/terraform-provider-snowflake pull request #1334
Opened 2022-11-01 22:02 UTC by cinglish

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

2022-11-01 22:10 UTC, cinglish commented
This PR adds an attribute, revert_ownership_to, to both the user_ownership_grant and role_ownership_grant resources to transfer ownership to the provided role instead of defaulting to ACCOUNTADMIN. This fixes an issue we were facing in which we could not run terraform destroy successfully due to DROP ROLE statements failing on snowflake_role resources after their respective snowflake_role_ownership resources were deleted.

2022-11-02 08:47 UTC, sfc-gh-swinkler requested changes

2022-11-02 08:47 UTC, sfc-gh-swinkler commented on pkg/resources/role_ownership_grant.go
> +	"revert_ownership_to": {
for consistency perhaps this should be renamed to:
`revert_ownership_to_role_name`
alternatively:
`default_owner_role_name`

2022-11-07 19:35 UTC, sfc-gh-swinkler commented
/ok-to-test sha=d03a4ea

2022-11-07 21:13 UTC, sfc-gh-swinkler commented
@cinglish can you please run `make docs` again? since the schema changed after you renamed the attribute. thanks in advance!

2022-11-07 21:48 UTC, sfc-gh-swinkler approved these changes

2022-11-07 21:48 UTC, merged

2022-11-07 21:48 UTC, sfc-gh-swinkler commented
@cinglish thank you for your contribution!