support different tag association queries for COLUMN object types
Snowflake-Labs/terraform-provider-snowflake pull request #1380
Opened 2022-11-21 23:31 UTC by rmorris1218

This is intended to close #1201 by implementing some logic to handle the slightly different query needed for `COLUMN` tag associations vs. other object types.

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

2022-12-07 18:40 UTC, sfc-gh-swinkler commented
/ok-to-test sha=be77caa

2022-12-22 20:11 UTC, sfc-gh-swinkler commented
/ok-to-test sha=be77caa

2022-12-22 21:42 UTC, sfc-gh-swinkler commented
```
    tag_association_test.go:45: 
        	Error Trace:	/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/snowflake/tag_association_test.go:45
        	Error:      	Not equal: 
        	            	expected: "c"
        	            	actual  : "\"a\".\"b\".\"c\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-c
        	            	+"a"."b"."c"
        	Test:       	TestTableColumnName
```
Hello @rmorris1218! There is a minor issue with the test case TestTableColumnName. If you could please correct then we can get this PR merged.

2023-01-13 19:19 UTC, AndresPeralta requested changes
We are calling ALTER TABLE x ALTER COLUMN y when should be:
ALTER TABLE x MODIFY COLUMN y

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association.go
> +		return fmt.Sprintf(`ALTER TABLE %v ALTER COLUMN %v SET TAG "%v"."%v"."%v" = '%v'`, tableName, columnName, tb.databaseName, tb.schemaName, tb.tagName, EscapeString(tb.tagValue))
We should change the `ALTER COLUMN` with `MODIFY COLUMN`
```suggestion
		return fmt.Sprintf(`ALTER TABLE %v MODIFY COLUMN %v SET TAG "%v"."%v"."%v" = '%v'`, tableName, columnName, tb.databaseName, tb.schemaName, tb.tagName, EscapeString(tb.tagValue))
```

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association.go
> +		return fmt.Sprintf(`ALTER TABLE %v ALTER COLUMN %v UNSET TAG "%v"."%v"."%v"`, tableName, columnName, tb.databaseName, tb.schemaName, tb.tagName)
```suggestion
		return fmt.Sprintf(`ALTER TABLE %v MODIFY COLUMN %v UNSET TAG "%v"."%v"."%v"`, tableName, columnName, tb.databaseName, tb.schemaName, tb.tagName)
```

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association_test.go
> +			ExpectedCreate: `ALTER TABLE "test_db"."test_schema"."test_table" ALTER COLUMN important SET TAG "test_db"."test_schema"."sensitive" = 'true'`,
same here:
```suggestion
			ExpectedCreate: `ALTER TABLE "test_db"."test_schema"."test_table" MODIFY COLUMN important SET TAG "test_db"."test_schema"."sensitive" = 'true'`,
```

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association_test.go
> +			ExpectedDrop:   `ALTER TABLE "test_db"."test_schema"."test_table" ALTER COLUMN important UNSET TAG "test_db"."test_schema"."sensitive"`},
```suggestion
			ExpectedDrop:   `ALTER TABLE "test_db"."test_schema"."test_table" MODIFY COLUMN important UNSET TAG "test_db"."test_schema"."sensitive"`},
```

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association_test.go
> +			ExpectedCreate: `ALTER TABLE "OPERATION_DB"."SECURITY"."test_table" ALTER COLUMN important SET TAG "OPERATION_DB"."SECURITY"."PII_2" = 'true'`,
```suggestion
			ExpectedCreate: `ALTER TABLE "OPERATION_DB"."SECURITY"."test_table" MODIFY COLUMN important SET TAG "OPERATION_DB"."SECURITY"."PII_2" = 'true'`,
```

2023-01-13 19:19 UTC, AndresPeralta commented on pkg/snowflake/tag_association_test.go
> +			ExpectedDrop:   `ALTER TABLE "OPERATION_DB"."SECURITY"."test_table" ALTER COLUMN important UNSET TAG "OPERATION_DB"."SECURITY"."PII_2"`},
```suggestion
			ExpectedDrop:   `ALTER TABLE "OPERATION_DB"."SECURITY"."test_table" MODIFY COLUMN important UNSET TAG "OPERATION_DB"."SECURITY"."PII_2"`},
```

2023-01-18 00:32 UTC, rmorris1218 commented
> We are calling ALTER TABLE x ALTER COLUMN y when should be: ALTER TABLE x MODIFY COLUMN y

Thanks for the heads up! Updated the syntax for these.

2023-01-18 17:48 UTC, ldardick commented
@sfc-gh-swinkler  any chance this can be reviewed by the Snowflake team? It's a blocker for us and the requested changes seems to be already applied by the owner. Let me know if I can help  with something

2023-01-19 13:55 UTC, AndresPeralta approved these changes

2023-01-27 16:14 UTC, ldardick commented
/ok-to-test sha=9206993

2023-02-01 00:33 UTC, scottwinkler commented
/ok-to-test sha=0c041916

2023-02-01 00:53 UTC, scottwinkler commented
/ok-to-test sha=0c04191

2023-02-01 00:55 UTC, sfc-gh-swinkler commented
/ok-to-test sha=0c04191

2023-02-01 01:02 UTC, sfc-gh-swinkler commented
Sorry this slipped through the cracks. This looks okay to me. what i will do is merge it and resolve any workflow errors myself and get in the next release.

2023-02-01 01:02 UTC, merged