feat: email notification integration
Snowflake-Labs/terraform-provider-snowflake pull request #1720
Opened 2023-04-14 08:35 UTC by mlorek

feat: email notification integration - #1693

## Test Plan

* [ x] acceptance tests

## References
https://docs.snowflake.com/en/user-guide/email-stored-procedures

*

2023-04-17 18:01 UTC, sfc-gh-swinkler requested changes
looks good, just a few minor changes requested

2023-04-17 18:01 UTC, sfc-gh-swinkler commented on pkg/resources/email_notification_integration_acceptance_test.go
> +				),
you need to add an import test. Something like:

			// IMPORT
	```
		{
				ResourceName:     "snowflake_email_notification_integration.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
```

2023-04-18 05:36 UTC, mlorek commented on pkg/resources/email_notification_integration.go
> +		// Default:  true,
'Default cannot be set with Required'

2023-04-28 23:28 UTC, sfc-gh-swinkler commented
Thanks @mlorek, this looks good!.  I have been working on a new design for the Snowflake SDK to replace the "snowflake" package. You can learn more about it here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1767. Would appreciate if you had any feedback / would be able to contribute using this new design pattern in the future.

2023-04-29 00:06 UTC, sfc-gh-swinkler approved these changes
Thanks @mlorek !

2023-04-29 00:06 UTC, merged