fix: warehouse resource
Snowflake-Labs/terraform-provider-snowflake pull request #1915
Opened 2023-06-27 11:39 UTC by sivchari

The following plan was output.

```terraform
  ~ resource "snowflake_warehouse" "query-2xlarge" {
        id                                  = "DEV_GARNET_WH_QUERY_2XLARGE"
        name                                = "DEV_GARNET_WH_QUERY_2XLARGE"
      ~ warehouse_size                      = "2XLARGE" -> "XXLARGE"
        # (13 unchanged attributes hidden)
    }
```

I fixed warehouse size definition and fixed Update/Delete resource to save the latest tfstate.

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

2023-06-29 21:05 UTC, sfc-gh-ngaberel commented
/ok-to-test d1956bc09c14313ffb812ea777e39993ef7fc9de

2023-06-29 21:06 UTC, sfc-gh-ngaberel approved these changes

2023-06-29 21:11 UTC, sfc-gh-ngaberel commented
/ok-to-test sha=d1956bc09c14313ffb812ea777e39993ef7fc9de

2023-06-30 05:06 UTC, sivchari commented
/ok-to-test sha=d1956bc09c14313ffb812ea777e39993ef7fc9de

2023-06-30 05:08 UTC, sivchari commented
Please rerun 🙏

2023-06-30 16:44 UTC, sfc-gh-ngaberel commented
@sivchari sorry we were having issues with our CI infrastructure yesterday, it's back to normal now, I should be able to merge this today. :)

2023-06-30 21:12 UTC, sfc-gh-ngaberel commented
/ok-to-test sha=3350642c4f1244282764264a2de4400cf5bcee3f

2023-08-25 08:31 UTC, sivchari commented
@sfc-gh-swinkler @sfc-gh-ngaberel 

Can you merge this ? Thanks.

2023-08-29 20:05 UTC, sfc-gh-swinkler requested changes

2023-08-29 20:05 UTC, sfc-gh-swinkler commented on pkg/resources/warehouse.go
> +	return ReadWarehouse(d, meta)
theres no reason to read the warehouse after dropping it.

2023-10-03 10:15 UTC, sfc-gh-asawicki commented
Hi @sivchari! Will you introduce the change that @sfc-gh-swinkler has requested?

2024-07-11 10:59 UTC, sfc-gh-asawicki commented
Closign because warehouse resource was deeply redesigned in v0.93.0.

2024-07-11 10:59 UTC, closed without merging