Update table.md
Snowflake-Labs/terraform-provider-snowflake pull request #2046
Opened 2023-09-04 17:46 UTC by jkodroff

Add a link to the Snowflake docs which contain all the valid column types.

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

2023-09-20 07:10 UTC, sfc-gh-jcieslak approved these changes

2023-10-03 11:52 UTC, sfc-gh-asawicki requested changes

2023-10-03 11:52 UTC, sfc-gh-asawicki commented on docs/resources/table.md
> +- `type` (String) Column type, e.g. VARIANT. For a full list of column types, see [Summary of Data Types](https://docs.snowflake.com/en/sql-reference/intro-summary-data-types).
This file is auto-generated, so it should not be updated directly.

You can instead add it to `pkg/resources/table.go` and run `make docs`; that will update this file.

2023-10-03 11:57 UTC, sfc-gh-asawicki commented
@jkodroff, thanks for the suggestion!

I have added one comment during the review; can you correct it accordingly?

Also, please add the `docs: ` prefix to the name of the pull request.

2024-07-12 13:34 UTC, closed without merging