Go generator dsl
Snowflake-Labs/terraform-provider-snowflake pull request #2061
Opened 2023-09-19 09:42 UTC by sfc-gh-jcieslak

## Summary

This change contains a migration of Network Policy to the new SDK, but the main focus was on improving generator API and extending its capabilities to generated more boilterplate code. I must say that although a lot changed, there's still much work to do in the generator, but I think that after this change we'll have more foundation to work with and to add to. I think the most important thing for this pr is to check if everything is generated / written correctly for Network Policy and to correct / fix my changes to the generator API and internal changes, so after merge we could start writing more resources with it and change as little things as possible (with capability to extend the generator without major changes to the API / internal structure).

## Test Plan
* [x] unit tests (validation + implementation)
* [x] integration tests

## References
Create Network Policy - https://docs.snowflake.com/en/sql-reference/sql/create-network-policy

2023-09-27 10:35 UTC, sfc-gh-asawicki requested changes

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/example/database_role_dto_gen.go
> +//go:generate go run ./dto-builder-generator/main.go
should this path really change?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/example/database_role_gen.go
> +	Comment string `ddl:"keyword" sql:"COMMENT"`
why bool -> string here?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/example/database_role_validations_gen.go
> +	if everyValueSet(opts.Rename, opts.Set, opts.Unset) {
why every and not exactly one as was before?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/file_util.go
> -func WriteCodeToFile(buffer *bytes.Buffer, fileName string) {
I prefer to have it in separate util, not in util.go, because there are different levels of utils there.

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/identifier_builders.go
> +func (v *queryStruct) SelfIdentifier() *queryStruct {
I wonder if for clarity in DSL this shouldn't be named just `Name()`. WDYT?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/identifier_builders.go
> +	if len(kind) > 0 && kind[0] != '*' {
hmm, there was already method `KindNoPtr()` on `*Field`, which utilises just cutPrefix, so maybe it would be more consistent to implement it the same way.

This is nit-picking, you can close it.

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/operation.go
> +	ShowMapping     *Mapping
Please add descriptions to each new field in this struct.

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/interface.go
> +type Interface struct {
I like the file split, but next time, please do not do it in the same change with refactoring and adding functionality because it is much harder to review.

Close after reading.

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/main.go
> +	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
strange that our linter is not complaining here about the import not at the bottom 🔍

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/validation.go
> +func (v *Validation) ReturnedError() string {
you have changed this method in other PR, so maybe let's adjust it.

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/util.go
> +type TagBuilder struct {
tag builder should be in separate file?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/query_struct.go
> +type queryStruct struct {
it would be nice later to do a bit of a cleanup in this directory, so we have clear separation between DSL files, model files, etc. Because now looking here, one may wonder, why we need both Field and queryStruct.

Can you add it to README?

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/README.md
> +- add arguments to the generator, so we'll be able to specify which files should be generated / re-generated,
I would argue if this is the top priority (and this is second on the essentials list)

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/README.md
> +  - example implementation - StringTyper implements Typer and all the KindOf... functions use StringTyper to return Typer easily - https://go.dev/play/p/TZZgSkkHw_M
please add here a point about keeping track of generated structs, because the implementation now is not the prettiest one

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/templates.go
> +{{ range .Operations }}
this have to be cleaned up, please add to essentials (I know there is a template separation one, but also a rework here would be nice to make it much simpler template)

2023-09-27 10:35 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/templates.go
> +//go:generate go run ./dto-builder-generator/main.go
this should be parametrised, because now example won't work (I mentioned it in another comment).

You can add it as essential.

2023-09-28 08:55 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/main.go
> +	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
oh, you are right

2023-09-28 09:02 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/example/database_role_gen.go
> +	Comment string `ddl:"keyword" sql:"COMMENT"`
Still string :sadeg:

2023-09-28 09:05 UTC, sfc-gh-asawicki approved these changes

2023-09-28 09:05 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/generator/templates.go
> +			assertOptsInvalidJoinedErrors(t, opts, {{ .ReturnedError }})
you missed one .ReturnedError here (add $field)

2023-09-28 09:21 UTC, sfc-gh-jcieslak commented on pkg/sdk/poc/example/database_role_gen.go
> +	Comment string `ddl:"keyword" sql:"COMMENT"`
![fixed](https://media.giphy.com/media/VeSvZhPrqgZxx2KpOA/giphy.gif)

2023-09-28 09:37 UTC, sfc-gh-asawicki approved these changes

2023-09-28 09:37 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/example/database_role_dto_gen.go
> +	Name DatabaseObjectIdentifier
they should still be required

2023-09-28 09:37 UTC, sfc-gh-asawicki commented on pkg/sdk/poc/main.go
> +	//runAllTemplatesToStdOut(definition)
😠

2023-09-28 09:49 UTC, sfc-gh-asawicki approved these changes

2023-09-28 11:10 UTC, merged