Use network policy from sdk
Snowflake-Labs/terraform-provider-snowflake pull request #2087
Opened 2023-10-02 09:33 UTC by sfc-gh-jcieslak

2023-10-02 15:01 UTC, sfc-gh-asawicki requested changes

2023-10-02 15:01 UTC, sfc-gh-asawicki commented on pkg/resources/network_policy.go
> +	for _, np := range networkPolicies {
findOne?

2023-10-03 06:02 UTC, sfc-gh-jcieslak commented on pkg/resources/network_policy.go
> -			q := builder.ChangeComment(c)
No, because it's used in the `resources/network_policy_attachment.go`

2023-10-09 07:19 UTC, sfc-gh-asawicki commented on pkg/resources/network_policy.go
> -			q := builder.ChangeComment(c)
Yeah, but not all of the methods are used there

2023-10-09 07:49 UTC, sfc-gh-jcieslak commented on pkg/resources/network_policy.go
> -			q := builder.ChangeComment(c)
Removed unused methods and tests

2023-10-09 08:03 UTC, sfc-gh-asawicki approved these changes

2023-10-10 08:22 UTC, sfc-gh-swinkler commented
LGTM

2023-10-12 11:48 UTC, merged