feat: Add "CREATE DYNAMIC TABLE" to schema_grant
Snowflake-Labs/terraform-provider-snowflake pull request #2144
Opened 2023-10-22 16:37 UTC by kenkoooo

Add `CREATE DYNAMIC TABLE` to schema_grant to allow users to create a schema with this privilege.

## References

* #1922

2023-10-24 02:06 UTC, kenkoooo commented
@sfc-gh-asawicki
Hi, if I missed something I needed to do before creating a PR, please let me know! Thank you!

2023-10-26 01:11 UTC, kenkoooo commented
@sfc-gh-asawicki @sfc-gh-jcieslak @sfc-gh-swinkler 
Hi, would you mind reviewing this PR or letting me know if I missed anything required for requesting reviews? Thank you!

2023-10-27 07:45 UTC, sfc-gh-swinkler submitted a review, later dismissed

2023-10-30 16:43 UTC, sfc-gh-asawicki requested changes

2023-10-30 16:43 UTC, sfc-gh-asawicki commented on pkg/resources/schema_grant.go
> +	privilegeCreateDynamicTable,
For completeness, it should also be added to the `pkg/sdk/privileges.go` file (`SchemaPrivilege` type).

2023-11-01 01:05 UTC, kenkoooo commented
@sfc-gh-asawicki @sfc-gh-swinkler 
Thank you for your review! I have added it to the file. Would you mind reviewing it again?

2023-11-09 13:18 UTC, sfc-gh-asawicki approved these changes

2023-11-09 13:40 UTC, sfc-gh-asawicki commented
/ok-to-test sha=e18458fb5b04762b5bc52cdd3a63669a2e680b61

2023-11-09 13:41 UTC, sfc-gh-asawicki commented
/ok-to-test sha=110e3c5882fb0437be06f7a9b033df805ecc0978

2023-11-09 14:15 UTC, merged

2023-11-11 06:39 UTC, kenkoooo commented
Thank you guys for working on it!