fix: allow DT warehouse to be updated in-place
Snowflake-Labs/terraform-provider-snowflake pull request #2439
Opened 2024-01-27 22:15 UTC by sonya

Dynamic table warehouses can be updated in-place with an ALTER DYNAMIC TABLE statement. The terraform resource was requiring the DT to be dropped and recreated in order to change the warehouse, but this is not necessary.

This commit removes the ForceNew modifier on the "warehouse" parameter so that users can easily change the warehouse. This is a setting that users may want to easily change for cost allocation purposes.

## Test Plan
* [ ] tested by running `terraform apply` and `terraform plan` on an existing stack with warehouse changes, observed that dynamic tables were updated in place, and `ALTER DYNAMIC TABLE` was run in Snowflake

## References

Documentation for `ALTER DYNAMIC TABLE` command: https://docs.snowflake.com/en/sql-reference/sql/alter-dynamic-table

2024-01-29 16:51 UTC, sfc-gh-asawicki commented
Hey @sonya. Thanks for the PR. This week is pretty tough for us, I will check the PR next week.

2024-02-07 11:04 UTC, sfc-gh-jcieslak submitted a review, later dismissed

2024-02-08 11:11 UTC, sfc-gh-asawicki requested changes
Hey @sonya. Thanks for the contribution.

I have just a small comment with the missing test, and we can merge it after!

2024-02-08 11:11 UTC, sfc-gh-asawicki commented on pkg/resources/dynamic_table.go
> -		ForceNew:    true,
Please add the `warehouse` param change in the `TestAcc_DynamicTable_basic` test.

2024-02-12 05:49 UTC, sonya commented
Added the field to the basic acceptance test. I'm not sure if that's sufficient to demonstrate that the DT doesn't get destroyed and recreated. I did some more work in #2437 on being able to tell if a change caused a replace (but I might be missing a much more obvious way)

2024-02-12 10:40 UTC, sfc-gh-asawicki commented
Thanks, I will check it today.

2024-02-12 13:40 UTC, sfc-gh-jcieslak approved these changes
Maybe the second warehouse could be named TestSecondaryWarehouseName, but It's just a cosmetic change and we can do it later. Thanks for the contribution!

2024-02-12 13:40 UTC, sfc-gh-asawicki approved these changes

2024-02-12 13:41 UTC, sfc-gh-asawicki commented
/ok-to-test sha=6cea1521bf8037b7252217a47fdd6a3c3ac69cc2

2024-02-12 15:31 UTC, sfc-gh-asawicki commented
/ok-to-test sha=e8ee7b4d9b16c645df6765750c81008cc20febd0

2024-02-12 16:10 UTC, merged

2024-02-12 16:11 UTC, sfc-gh-asawicki commented
I have merged the change. Thank you for your contribution @sonya!