Adds case statement for ObjectTypeUser in ShowObjectParameter.
Snowflake-Labs/terraform-provider-snowflake pull request #2675
Opened 2024-04-04 16:47 UTC by cmonty-paypal

When issuing `object_type = "USER"` via the `snowflake_object_parameter` resource  the `ShowObjectParameter` function did not handle the `ObjectTypeUser` which led to failures.

## Test Plan
* [x] acceptance tests

## References
* Fixes #2669

2024-04-10 12:46 UTC, sfc-gh-jcieslak submitted a review, later dismissed
Hey, looks good. Thank you for the contribution :)

2024-04-10 12:46 UTC, sfc-gh-asawicki requested changes
I like the change, only one small comment left.

2024-04-10 12:46 UTC, sfc-gh-asawicki commented on pkg/acceptance/testing.go
> +	TestUserName       = "terraform_test_user"
Please do not create the user in this global setup but create one in PreConfig or by simply adding `resource snowflake_user test_user {...}` to the config used in the test.

2024-04-10 21:57 UTC, cmonty-paypal commented
> I like the change, only one small comment left.

Thanks for the feedback, I refactored the test user.

2024-04-11 05:52 UTC, sfc-gh-asawicki approved these changes

2024-04-11 05:53 UTC, sfc-gh-asawicki commented
/ok-to-test sha=a0d8595870f1e37c4223141e96139a96331b6623

2024-04-11 06:55 UTC, merged

2024-04-11 06:56 UTC, sfc-gh-asawicki commented
Merged. Thanks for the contribution @cmonty-paypal! 🎉