chore: Initialize the SDK client in fewer places
Snowflake-Labs/terraform-provider-snowflake pull request #2710
Opened 2024-04-15 10:03 UTC by sfc-gh-asawicki

TODO

2024-04-15 13:24 UTC, sfc-gh-jcieslak requested changes

2024-04-15 13:24 UTC, sfc-gh-jcieslak commented on pkg/acceptance/testing.go
> +	return atc.client
secondaryClient*

2024-04-15 13:43 UTC, sfc-gh-asawicki commented on pkg/acceptance/testing.go
> +	return atc.client
🤦 fixed

2024-04-16 06:37 UTC, sfc-gh-jcieslak approved these changes

2024-04-16 07:11 UTC, merged