feat: datasource database role
Snowflake-Labs/terraform-provider-snowflake pull request #2731
Opened 2024-04-19 12:30 UTC by mlorek

Adding datasource - single database role

## Test Plan

* [ v] acceptance tests

## References

*

2024-05-08 11:29 UTC, sfc-gh-jmichalak requested changes

2024-05-08 11:29 UTC, sfc-gh-jmichalak commented on pkg/datasources/database_role_acceptance_test.go
> +            comment = "test"
Please fix formatting of Terraform config.

2024-05-08 11:29 UTC, sfc-gh-jmichalak commented on pkg/datasources/database_role.go
> +	extractedDatabaseRoles, err := client.DatabaseRoles.Show(ctx, showRequest)
You can use  `client.DatabaseRoles.ShowByID`, that returns one DatabaseRole. See `database.go` file for reference.

2024-05-08 12:14 UTC, sfc-gh-jcieslak requested changes
Thank you for submitting a PR. We had a few suggestions, but after that we'll be good to merge 🙂.

2024-05-08 12:14 UTC, sfc-gh-jcieslak commented on pkg/datasources/database_role.go
> +	"role": {
Please change the `role` field to `name`, so it will match with other data sources.

2024-05-08 12:14 UTC, sfc-gh-jcieslak commented on pkg/datasources/database_role.go
> +	return err
There should be no error so `return nil` and please set the id (`d.SetId("database_role_read")`) before the last return.

2024-05-10 10:06 UTC, sfc-gh-jcieslak approved these changes
Approved, Thanks again for the contribution 🙂

2024-05-10 10:08 UTC, sfc-gh-jcieslak commented
/ok-to-test sha=c223343d0b0102faa7ab8d16b2c8a9d362cab26e

2024-05-10 10:11 UTC, sfc-gh-jcieslak commented on pkg/datasources/database_role.go
> +var databaseRoleSchema = map[string]*schema.Schema{
docs have to be generated for this one, so just run `make pre-push` and the documentation should be generated. If any error pops up, refer to the [contribution guidelines](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md#making-a-contribution).

2024-05-10 10:13 UTC, sfc-gh-jcieslak requested changes
ref to the last comment

2024-05-13 07:14 UTC, sfc-gh-jcieslak commented
/ok-to-test sha=e9108ff781c12a8d378d54ec8bdb8cf63ef7588d

2024-05-14 10:46 UTC, sfc-gh-jcieslak commented
/ok-to-test sha=7623db621e910b429a6be0f4e186fe2aafbd8bfb

2024-05-15 09:01 UTC, sfc-gh-jcieslak approved these changes

2024-05-15 09:01 UTC, merged

2024-05-15 09:06 UTC, sfc-gh-jcieslak commented
Hey 👋 
Everything looked great, the pr was merged. Again, thank you for your contribution!