chore: Apply new resource conventions to scim integration
Snowflake-Labs/terraform-provider-snowflake pull request #2891
Opened 2024-06-27 12:19 UTC by sfc-gh-jcieslak

Done in the PR:
- Described changes in Migration Guide and description for changed fields (only one field; `sync_password`)
- Added SHOW and DESCRIBE outputs to the scim integration schema
- Applied the new resource conventions to the scim integration
- Added DESCRIBE helpers for the new convention and DESCRIBE schema for the scim integration

2024-06-27 13:05 UTC, sfc-gh-jmichalak requested changes

2024-06-27 14:16 UTC, sfc-gh-jcieslak commented on pkg/schemas/security_integration.go
> +var DescribeSecurityIntegrationSchema = map[string]*schema.Schema{
Done

2024-06-27 14:19 UTC, sfc-gh-jcieslak commented on pkg/resources/diff_suppressions.go
> +					log.Printf("[DEBUG] IgnoreChangeToCurrentSnowflakeValueInDescribe: value for key %s is %v, new value is %s, comparison result is: %t", keyInDescribeOutput, newValueInDescribe, new, new == fmt.Sp
That's also in the "original" method and I would leave it for debugging purposes

2024-06-27 14:19 UTC, sfc-gh-jcieslak commented on pkg/schemas/security_integration.go
> +	DescribeSecurityIntegrationSchemaKeys = make([]string, 0, len(DescribeSecurityIntegrationSchema))
I removed those because they were not useful

2024-06-27 14:20 UTC, sfc-gh-jcieslak commented on pkg/schemas/security_integration.go
> +			"COMMENT":
Done

2024-06-27 14:20 UTC, sfc-gh-jcieslak commented on pkg/resources/warehouse_rework_show_output_proposal.go
> +	if describeOutput, ok := d.GetOk(showOutputAttributeName); ok {
+1, done

2024-06-27 14:21 UTC, sfc-gh-jcieslak commented on pkg/resources/scim_integration.go
> +		Description: "Outputs the result of `SHOW SECURITY INTEGRATIONS` for the given security integration.",
Done

2024-06-28 06:57 UTC, sfc-gh-jmichalak approved these changes

2024-06-28 08:02 UTC, sfc-gh-asawicki approved these changes

2024-06-28 08:02 UTC, sfc-gh-asawicki commented on pkg/resources/scim_integration_acceptance_test.go
> +						planchecks.ExpectChange("snowflake_scim_integration.test", "sync_password", tfjson.ActionUpdate, nil, sdk.String("unknown")),
Please check (in the next PR) if we can avoid having a change by adding an unknown in the upgrader if the key was not present in the previous state at all. **EDIT**: after discussion, I will check it with other options in my PR.

2024-06-28 08:02 UTC, sfc-gh-asawicki commented on MIGRATION_GUIDE.md
> +#### *(behavior change)* Changed behavior of `sync_password`
should we also add info about expected changes after bumping version? (because of the state handling changes - consult warehouse) - next Pr is fine

2024-06-28 08:06 UTC, sfc-gh-jcieslak commented on pkg/resources/scim_integration_state_upgraders.go
> +func v091ScimIntegrationStateUpgrader(ctx context.Context, rawState map[string]any, meta any) (map[string]any, error) {
I was already changed in the SAML pr

2024-06-28 08:07 UTC, merged