feat: Rework account parameter resource
Snowflake-Labs/terraform-provider-snowflake pull request #3264
Opened 2024-12-10 15:18 UTC by sfc-gh-jmichalak

- rework account parameter resource
- use UNSET in resource deletion
- add missing docs
- add missing functions in the sdk
- 

## Test Plan

* [x] acceptance tests

* [ ] …

## References

https://docs.snowflake.com/en/sql-reference/parameters

## TODO
- support all of the account parameters
- add tests for all of the supported account parameters
- check unsetting with a proper checkDestroy

2024-12-11 10:25 UTC, sfc-gh-jcieslak approved these changes

2024-12-11 17:34 UTC, sfc-gh-asawicki requested changes
The tests need fixing, so maybe the TODOs with more parameters can be handled in this one?

2024-12-12 11:21 UTC, sfc-gh-jmichalak commented on pkg/resources/account_parameter_acceptance_test.go
> +// TODO(next pr): add more acc tests
Initially I was planning to test setting/unsetting all of the parameters on a separate account (after v1).

2024-12-12 11:56 UTC, sfc-gh-jmichalak commented on docs/resources/account_parameter.md
> +Resource used to manage current account parameters. For more information, check [parameters documentation](https://docs.snowflake.com/en/sql-reference/parameters). To manage the whole account resourc
Done.

2024-12-12 11:57 UTC, sfc-gh-jmichalak commented on pkg/sdk/parameters.go
> +	// TODO(next pr): add remaining parameters
Added some more based on switches in parameter_impl.go. This should cover all of the parameters that had been supported before, so we shouldn't have any downgrade. I'll do a more thorough research later.

2024-12-12 12:23 UTC, sfc-gh-jmichalak commented on pkg/resources/account_parameter_acceptance_test.go
> +// TODO(next pr): check unsetting in CheckDestroy
Done.

2024-12-12 13:01 UTC, sfc-gh-jcieslak submitted a review, later dismissed

2024-12-12 13:09 UTC, sfc-gh-asawicki approved these changes

2024-12-12 14:22 UTC, sfc-gh-asawicki approved these changes

2024-12-12 14:30 UTC, sfc-gh-jcieslak approved these changes

2024-12-12 14:39 UTC, merged